<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_PreSelectShippingPayment
 * @author    Extension Team
 * @copyright Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php 
    $defaultShipping = $block->getShippingDefault();
    $defaultPayment = $block->getPaymentDefault();
    $shippingPosition = $block->getShippingPosition();
    $paymentPosition = $block->getPaymentPosition();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Bss_PreSelectShippingPayment/js/checkout_process": {
                "defaultShipping": "<?php echo $defaultShipping; ?>",
                "defaultPayment" : "<?php echo $defaultPayment; ?>",
                "positionShipping" : "<?php echo $shippingPosition; ?>",
                "positionPayment" : "<?php echo $paymentPosition; ?>"
            }
        }
    }
</script>