<?php
/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>

<div class="frame">
    <div class="line">
        <div class="form-box block block-customer-forgot-password">
            <div class="block-title">
                <h2 class="title" id="block-customer-login-heading" role="heading" aria-level="2"><span><?php /* @escapeNotVerified */ echo __('Recover Password') ?></span></h2>
            </div>
            <form class="form password forget"
                  action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
                  method="post"
                  id="form-validate"
                  data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                    <div class="field note"><?php /* @escapeNotVerified */ echo __('Please enter your email address below to receive a password reset link.'); ?></div>
                    <div class="field email required">
                        <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                        <div class="control">
                            <input type="email" name="email" placeholder="Email Address"  alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info'); ?>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action submit primary btn-full btn  btn-default  btn-rounded icon-right"><span><?php /* @escapeNotVerified */ echo __('Reset My Password') ?></span></button>
                    </div>
                    <div class="secondary">
                        <a class="action back" href="<?= $block->escapeUrl($block->getUrl('searchcustomeremail/recoveremail/recover')) ?>"><?= $block->escapeHtml(__('Forgot Email')) ?></a>
                    </div>
                </div>
            </form>
            </div>

    </div>
</div>

