<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$repository = $objectManager->get('Magento\Framework\View\Asset\Repository');

if ($customerSession->isLoggedIn()):
    $order_id = $this->getRequest()->getParam('order_id');
    if($order_id):
        $order = $objectManager->create('Magento\Sales\Model\Order')->load($order_id);

        if($order->getData('status') != 'processing'): 
            if($order->getPayment()):
                if($order->getPayment()->getAdditionalInformation('itaupix_boleto_url')):
                    $btn = '<a href="' . $order->getPayment()->getAdditionalInformation('itaupix_boleto_url') . '"  target="_blank" style="text-decoration: none;background-color: #32aeef;color: #fff;padding: 7px 20px;margin: 10px 0;display: block;width: 100px;text-align: center;border-radius: 5px;" >Gerar Boleto</a>';
                    ?>
                        <script>
                            require(['jquery', 'jquery/ui'], function($){
                                $('<?=$btn?>').insertAfter('.box.box-order-billing-method dl.payment-method');
                            });
                        </script>
                <?php endif; ?>
            <?php endif; ?>

                <?php if($itaupix_pix_qr_code = $order->getPayment()->getAdditionalInformation('itaupix_pix_qr_code')) : ?>
                    
					<?php
						$codPix = '<p><span id="msg-copy"></span><strong>1.</strong> Copie o código:<br /><input type="text" value="'. $itaupix_pix_qr_code .'" id="codeInput"><button onclick="copyQrCode()">Copiar Link PIX</button></p><p><strong>2.</strong> Abra o app do seu banco ou institução financeira e entre no ambiente <strong>PIX</strong>.</p><p><strong>3.</strong> Escolha a opção <strong>Pix copia e cola</strong>.</p><p><strong>4.</strong> Cole o código, confira as informações e finalize a compra.</p>';
					?>
					<script>
						require(['jquery', 'jquery/ui'], function($){
							$('<?=$codPix?>').insertAfter('.box.box-order-billing-method dl.payment-method');
						});
					</script>
					
					<script type="text/javascript">
					function copyQrCode() {
						var copyText = document.getElementById("codeInput");
						copyText.select();
						copyText.setSelectionRange(0, 99999)
						document.execCommand("copy");
						document.getElementById('msg-copy').innerHTML += 'Copiado com Sucesso!';
					}
					var qrcode = '<?=$itaupix_pix_qr_code?>';
					window.onload = function() {
						new QRCode(document.getElementById("qrcode"), qrcode);
					}
					</script>
					
					<style>
						/* mobile */
						@media (max-width: 580px) {
						  #qrcode-container{
							  display: none;
						  }
						  #divinputcode{
							  display: block;
						  }
						}

						/* tablet laptop */
						@media (min-width: 581px) {
						  #qrcode-container{
							  display: block;
						  }
						  #divinputcode{
							  display: none;
						  }
						}
						
						#divinputcode p {
							padding: 10px;
						}

						#divinputcode input {
							padding: 20px;
							border-radius: 10px;
						}
						#divinputcode button {
							height: 50px;
							width: 100%;
							border-radius: 10px;
							background: #28ab6c;
							color: #fff;
						}

						div#qrcode img{
							width: 100%;
						}

						div#qrcode {
							float: left;
							width: 200px;
							margin: 0 20px 0 0;
						}

						div.pix{
							margin: 50px 0 0 0;
							min-height: 350px;
						}
						
						span#msg-copy {
							display: block;
							clear: both;
							text-align: center;
							color: #fff;
							font-weight: bold;
							background: #32bcad;
							margin: 0px 0px 10px 0px;
						}
						
					</style> 
            <?php endif; ?>

        <?php endif; ?>
    <?php endif;  ?>
<?php endif; ?>
