<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$order = $objectManager->create('Magento\Sales\Model\Order')->load($this->getRequest()->getParam('order_id'));
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
$scopeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
date_default_timezone_set('America/Sao_Paulo');

$data1 = date('Y-m-d', strtotime("+".(int) $scopeConfig->getValue('payment/itaushopline/days_duplicate', $storeScope)." days",strtotime($order->getData('created_at')))); 
$data2 = date('Y-m-d');

if($order->getData('status') != 'processing'):
    if($order->getPayment()->getAdditionalInformation('itau_shopline_data_genereted')):
        $btn = '<a href="'.$base_url.'statusItauShopline?create_boleto='.$order->getPayment()->getAdditionalInformation('itau_shopline_data_genereted').'"  target="_blank" style="text-decoration: none;background-color: #32aeef;color: #fff;padding: 7px 20px;margin: 10px 0;display: block;width: 100%;text-align: center;border-radius: 5px;" >Gerar Boleto</a>';;

        if(strtotime($data1) > strtotime($data2)){
            $btn .= ' <br><button onclick="generateNew()"  >Gerar 2º via Boleto</button>';
        }

?>

    <script>
        var d1 = document.querySelector('.box.box-order-billing-method dl.payment-method');
        d1.insertAdjacentHTML('afterend', '<?=$btn?>');
        function generateNew(){
        if (confirm("Deseja gerar 2° via de boleto")) {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                alert(this.responseText);
                location.reload();
            }
        };
        xmlhttp.open("GET", "<?=$base_url?>rest/all/V1/mestremage-itaushopline/viaboleto?param=<?=$this->getRequest()->getParam('order_id')?>", true);
        xmlhttp.send();
        }

    }
    </script>

    <?php endif; ?>
<?php endif; ?>


