<?php

$_emailFieldConfig = $this->helper('Semaio\AdvancedLogin\Helper\Login')->getEmailFieldConfig();
print_r($_emailFieldConfig);

?>
<?php if($block->checkCustomerStatus() || !$this->helper('MGS\Fbuilder\Helper\Data')->canShowFormLogin()): ?>
	<div class="login-form logged-customer">
		<button class="close-myaccount" id="close-myaccount"><span class="icon-cross2"></span></button>
		<?php echo $block->getChildHtml('top.link.header'); ?>
	</div>
<?php else: ?>
	<div class="login-form">
		<button class="close-myaccount" id="close-myaccount"><span class="icon-cross2"></span></button>
		<div class="block block-customer-login">
			<div class="block-title">
				<strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Login Your Account') ?></strong>
			</div>
			<div class="block-content" aria-labelledby="block-customer-login-heading">
				<form class="form form-login"
					  action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
					  method="post"
					  id="login-form-had"
					  data-mage-init='{"validation":{}}'>
					<?php echo $block->getBlockHtml('formkey'); ?>
					
					<select name="tipologin" id="tipologin">
						<option value="">Fazer login com</option>
						<option value="email">E-mail</option>
						<option value="cpf">CPF/CNPJ</option>
					</select> 
					
					<div class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" id="infos" style="display: none;">
						<div class="field email required">
							<div class="control">
								<input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="<?php echo $_emailFieldConfig['type']?>" class="input-text" title="<?php /* @escapeNotVerified */ echo __($_emailFieldConfig['label']) ?>" data-validate="<?php echo $_emailFieldConfig['data_validate']?>" placeholder="<?php echo __($_emailFieldConfig['label']); //echo __($_emailFieldConfig['label']);?>" >
							</div>
						</div>
						<div class="field password required">
							<div class="control">
								<input placeholder="<?php /* @escapeNotVerified */ echo __('Password') ?>" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass-had" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
								<a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot?') ?></span></a>
							</div>
						</div>
						<?php echo $block->getChildHtml('form.additional.info.header'); ?>
						<div class="actions-toolbar">
							<div class="primary">
								<button type="submit" class="action login btn btn-dark  btn-full" name="send" id="send2-had"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button>
							</div>
							<div class="secondary">
								<a class="action create primary" href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Create an account') ?></span></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
<?php endif ?>
<script type="text/javascript">
        require(['jquery'], function (jQuery) {
jQuery(document).ready(function(){
    jQuery('#tipologin').on('change', function() {
      if ( this.value == 'email')
      {
        jQuery("#infos").show();
		jQuery("#email").attr("placeholder", "Digite seu E-mail");
		jQuery("#email").attr("onkeyup", "");
		jQuery("#email").val('');  
		  
      }
      else if ( this.value == 'cpf')
      {
       jQuery("#infos").show();
	   jQuery("#email").attr("placeholder", "Digite seu CPF/CNPJ");
	   jQuery("#email").attr("onkeyup", "mascaraMutuario(this,cpfCnpj)");
	   jQuery("#email").val(''); 	  
		  
      }
		else {
			jQuery("#infos").hide();
		}
    });
});

/*			
jQuery('#email').keypress(function() {
  var dInput = this.value;
let firstChar = dInput.charAt(0) ;

  //console.log(dInput);
  //$('#output').text(dInput);
  if(jQuery.isNumeric(firstChar)){
        alert("numero");
             
         }else{
           alert("letra");  
         }
  });	
  */
			
});	
	
function mascaraMutuario(o,f){
    v_obj=o;
    v_fun=f;
	setTimeout('execmascara()',1)
}

function execmascara(){
	v_obj.value=v_fun(v_obj.value)
}

function cpfCnpj(v){
v=v.replace(/\D/g,"");

if (v.length > 0 && v.length <= 11) {
                    //CPF
	v=v.replace(/(\d{3})(\d)/,"$1.$2");

    v=v.replace(/(\d{3})(\d)/,"$1.$2");

    v=v.replace(/(\d{3})(\d{1,2})$/,"$1-$2")
} else {
    //CNPJ
    v=v.replace(/^(\d{2})(\d)/,"$1.$2");

    v=v.replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3");

    v=v.replace(/\.(\d{3})(\d)/,".$1/$2");

    v=v.replace(/(\d{4})(\d)/,"$1-$2");
}
	return v
}	
</script>

<style type="text/css">
#tipologin {
    background-color: #fafafa;
    margin-bottom: 20px;
    border: 1px solid #ebebeb;
    color: #999;
    transition: all .3s;
    font-weight: 300;
}
</style>


