<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
$scopeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');

$use_vat_id = '';
$taxvat = '';
if($scopeConfig->getValue("payment/boletoitau/use_vat_id", $storeScope)) {
    $use_vat_id = 1;

    $customerSession = $objectManager->create('Magento\Customer\Model\Session');
    if ($customerSession->isLoggedIn()) {
       $taxvat = $customerSession->getCustomer()->getTaxvat();
        $vat_id = '';
        $default_shipping = $customerSession->getCustomer()->getDefaultShipping();
        foreach($customerSession->getCustomer()->getAddresses() as $address){
            if($default_shipping == $address->getData('entity_id')){
                $vat_id = $address->getData('vat_id'); 
            break;
            }
        }
        if($vat_id){
            $taxvat = $vat_id;
        }
    }
}

?>

<script>
    var use_cpf = "<?=$use_vat_id?>";
    var cpf = "<?=$taxvat?>";
    require(['jquery', 'jquery/ui'], function($){
        $( document ).ready(function() {
            var existCondition = setInterval(function() {
                if ($('#formulario-boletoitau').length) {
                    clearInterval(existCondition);
                    if(use_cpf){
                        if(cpf){
                            $("input#boletoitau_cpf").val(cpf);

                        }else{
                            $('.form-shipping-address [name*="vat_id"]').keyup(function(){
                                var vat = $(this).val();
                                if(vat){
                                    $("input#boletoitau_cpf").val(vat);
                                }
                            })
                        }
                    }
                }
            }, 100);

        });
    });
</script>
